apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: {{ .Release.Name }}-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /live.php
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /status.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DB_HOST
          value: {{ .Values.db.host }}
        - name: DB_USER
          value: {{ .Values.db.user }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: password
        - name: DB_NAME
          value: {{ .Values.db.name }}
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE
