apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistentVolume.size }}
  storageClassName: {{ .Values.db.persistentVolume.storageClass }}
