apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-challenge-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-challenge-app
  template:
    metadata:
      labels:
        app: k8s-challenge-app
    spec:
      containers:
      - name: k8s-challenge-app
        image: alilikpo/k8s-challenge-app:v2
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mariadb-service  
        - name: DB_USER
          value: root  
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: password
        - name: DB_NAME
          value: ecomdb
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE            